netcon_web/core/urls.py
from django.urls import path

from core.views import HomePage


app_name = 'core'
urlpatterns = [
    path('', HomePage.as_view(), name='home_page'),
]

netcon_web/netcon_web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from core.views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('core.urls')),
    path('', HomePage.as_view(), name='home_page'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

netcon_web/core/models.py
from django.db import models

netcon_web/core/views.py
from django.shortcuts import render
from django.views import View


class HomePage(View):

    template_name = "home/index.html"

    def get(self, request):

        menu_data = [
        {
            'id': 1,
            'name': 'Menu 1',
            'subMenu': [
                {'name': 'Submenu 1', 'desc': 'Description 1',
                    'icon': 'path/to/icon1.svg'},
                {'name': 'Submenu 2', 'desc': 'Description 2',
                    'icon': 'path/to/icon2.svg'},
            ],
            'gridCols': 3,
        },
        {
            'id': 2,
            'name': 'Menu 2',
            'subMenu': [
                {'name': 'Submenu A', 'desc': 'Description A',
                    'icon': 'path/to/iconA.svg'},
                {'name': 'Submenu B', 'desc': 'Description B',
                    'icon': 'path/to/iconB.svg'},
            ],
            'gridCols': 2,
        },
        ]
        context = {
            'menu' : menu_data
        }
        return render(request=request, template_name=self.template_name,context=context)

netcon_web/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Netcon, UPS, Control cable" />
    <meta name="keywords" content="Netcon" />
    <meta name="author" content="netcon" />
    <title>Netcon</title>
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Manrope:wght@400;500;700&family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
    <link rel="shortcut icon" href="logos/favicon.png" />
    <link rel="stylesheet" href="{% static 'css/plugins.css' %}" />
    <link rel="stylesheet" href="{% static 'fonts/unicons/unicons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <link rel="stylesheet" href="{% static 'css/grape.css' %}" />
    <link rel="preload" href="{% static 'css/space.css' %}" as="style" onload="this.rel='stylesheet'" />
    <style>
      .swiper-container.nav-color .swiper-button,
      .swiper-container.nav-color .swiper-slide figure .item-link {
        background: #605dbae6 !important;
        color: #fff !important;
      }
      
      .swiper-container.nav-color .swiper-button:hover,
      .swiper-container.nav-color .swiper-slide figure .item-link:hover {
        background: #605dba !important;
      }
      
      @media (max-width: 991.98px) {
        .navbar-expand-lg .navbar-collapse .dropdown-toggle:after {
          color: #ffffff !important;
        }
      }
    </style>
  </head>

  <body>
    <div class="grow shrink-0">
      <header class="!absolute w-full">
        {% include 'header.html' %}
      </header>
      <!-- /header -->
   
        {% block body %}
        {% endblock %}
      </section>
      <!-- /section -->

      <!-- OTHER -->
      <!-- /section -->

      <!-- /section -->

      <footer class="!bg-[#21262c] shrink-0 mt-5">
        <div class="container py-16 xl:!py-20 lg:!py-20 md:!py-20">
          <div class="flex flex-wrap mx-[-15px] mt-[-30px] xl:mt-0 lg:mt-0">
            <div class="md:w-4/12 xl:w-3/12 lg:w-3/12 w-full flex-[0_0_auto] px-[15px] max-w-full xl:mt-0 lg:mt-0 mt-[30px]">
              <div class="widget text-[#cacaca]">
                <img loading="lazy" class="!mb-4" src="{%  static 'logos/favicon.png' %}" srcset="assets/logos/favicon.png 2x" width="45" alt="image" />
                <p class="!mb-4">
                  © 2021 Netcon. <br class="hidden xl:block lg:block text-[#cacaca]" />All rights reserved.
                </p>

                <!-- /.social -->
              </div>
              <!-- /.widget -->
            </div>
            <!-- /column -->
            <div class="md:w-4/12 xl:w-3/12 lg:w-3/12 w-full flex-[0_0_auto] px-[15px] max-w-full xl:mt-0 lg:mt-0 mt-[30px]">
              <div class="widget text-[#cacaca]">
                <h4 class="widget-title text-white !mb-3">Get in Touch</h4>
                <address class="xl:pr-20 xxl:!pr-28 not-italic leading-[inherit] block mb-4">Chennai, Tamil Nadu, India</address>
                <a class="text-[#cacaca] hover:text-[#3f78e0]" href="mailto:#">info@cieso.in</a><br /> 00 (91) 9567 9495 26
              </div>
              <!-- /.widget -->
            </div>
            <!-- /column -->
            <div class="md:w-4/12 xl:w-3/12 lg:w-3/12 w-full flex-[0_0_auto] px-[15px] max-w-full xl:mt-0 lg:mt-0 mt-[30px]">
              <div class="widget text-[#cacaca]">
                <h4 class="widget-title text-white !mb-3">Learn More</h4>
                <ul class="pl-0 list-none !mb-0">
                  <li>
                    <a class="text-[#cacaca] hover:text-[#3f78e0]" href="#">About Us</a>
                  </li>
                  <li class="mt-[0.35rem]">
                    <a class="text-[#cacaca] hover:text-[#3f78e0]" href="#">Our Story</a>
                  </li>
                  <li class="mt-[0.35rem]">
                    <a class="text-[#cacaca] hover:text-[#3f78e0]" href="#">Projects</a>
                  </li>
                  <li class="mt-[0.35rem]">
                    <a class="text-[#cacaca] hover:text-[#3f78e0]" href="#">Terms of Use</a>
                  </li>
                </ul>
              </div>
              <!-- /.widget -->
            </div>
            <!-- /column -->
            <div class="md:w-full xl:w-3/12 lg:w-3/12 w-full flex-[0_0_auto] px-[15px] max-w-full xl:mt-0 lg:mt-0 mt-[30px]">
              <div class="widget text-[#cacaca]">
                <h4 class="widget-title text-white !mb-3">Connect With Us</h4>
                <nav class="nav social social-white">
                  <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-twitter before:content-['\ed59'] !text-white text-[1rem]"></i></a>
                  <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-facebook-f before:content-['\eae2'] !text-white text-[1rem]"></i></a>
                  <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-dribbble before:content-['\eaa2'] !text-white text-[1rem]"></i></a>
                  <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-instagram before:content-['\eb9c'] !text-white text-[1rem]"></i></a>
                  <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-youtube before:content-['\edb5'] !text-white text-[1rem]"></i></a>
                </nav>
                <!-- /.newsletter-wrapper -->
              </div>
              <!-- /.widget -->
            </div>
            <!-- /column -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.container -->
      </footer>
    </div>
    <!-- /.content-wrapper -->
    <!-- FOOTER -->



    <!-- progress wrapper -->
    <div class="progress-wrap fixed w-[2.3rem] h-[2.3rem] cursor-pointer block shadow-[inset_0_0_0_0.1rem_rgba(128,130,134,0.25)] z-[1010] opacity-0 invisible translate-y-3 transition-all duration-[0.2s] ease-[linear,margin-right] delay-[0s] rounded-[100%] right-6 bottom-6 motion-reduce:transition-none after:absolute after:content-['\e951'] after:text-center after:leading-[2.3rem] after:text-[1.2rem] after:text-[#605dba] after:h-[2.3rem] after:w-[2.3rem] after:cursor-pointer after:block after:z-[1] after:transition-all after:duration-[0.2s] after:ease-linear after:left-0 after:top-0 motion-reduce:after:transition-none after:font-Unicons">
      <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path class="fill-none stroke-[#605dba] stroke-[4] box-border transition-all duration-[0.2s] ease-linear motion-reduce:transition-none" d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
      </svg>
    </div>

    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <script src="{% static 'js/framer-motion.min.js' %}"></script>
  </body>
</html>

netcon_web/core/templates/header2.html
{% load static %}
<nav class="navbar navbar-expand-lg center-nav transparent navbar-light">
  <div class="container xl:flex-row lg:flex-row !flex-nowrap items-center">
    <div class="navbar-brand w-full">
      <a href="{% url 'core:home_page' %}"><img loading="lazy" src="{% static 'logos/logo_netcon.png' %}" srcset="{% static 'logos/logo2x.png' %} 2x" alt="Netcon logo" /></a>
    </div>
    <div class="navbar-collapse offcanvas offcanvas-nav offcanvas-start">
      <div class="offcanvas-header xl:hidden lg:hidden flex items-center justify-between flex-row p-6">
        <h3 class="text-white xl:text-[1.5rem] !text-[calc(1.275rem_+_0.3vw)] !mb-0">Netcon</h3>
        <button type="button" class="btn-close btn-close-white mr-[-0.75rem] m-0 p-0 leading-none text-[#343f52] transition-all duration-[0.2s] ease-in-out border-0 motion-reduce:transition-none before:text-[1.05rem] before:content-['\ed3b'] before:w-[1.8rem] before:h-[1.8rem] before:leading-[1.8rem] before:shadow-none before:transition-[background] before:duration-[0.2s] before:ease-in-out before:flex before:justify-center before:items-center before:m-0 before:p-0 before:rounded-[100%] hover:no-underline bg-inherit before:bg-[rgba(255,255,255,.08)] before:font-Unicons hover:before:bg-[rgba(0,0,0,.11)] focus:outline-0" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body xl:!ml-auto lg:!ml-auto flex flex-col !h-full">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link font-bold tracking-[-0.01rem] hover:!text-[#605dba] after:!text-[#605dba]" href="index.php">Home</a>
          </li>

          <li class="nav-item dropdown dropdown-mega">
            <a class="nav-link dropdown-toggle font-bold tracking-[-0.01rem] hover:!text-[#605dba] after:!text-[#605dba]" href="#" data-bs-toggle="dropdown">Products</a>
            <ul class="dropdown-menu mega-menu mega-menu-dark mega-menu-img">
              <li class="mega-menu-content">
                <ul class="grid grid-cols-1 xl:grid-cols-6 lg:grid-cols-6 mx-0 xl:mx-[-15px] lg:mx-[-15px] xl:mt-[-20px] lg:mt-[-20px] !pl-0 list-none">
                  <li class="xl:px-[15px] xl:mt-[20px] lg:px-[15px] lg:mt-[20px]">
                    <a class="dropdown-item" href="{% url 'core:home_page' %}">
                      <div class="rounded img-svg hidden xl:block lg:block p-4 xl:!mb-2 lg:!mb-2">
                        <img loading="lazy" class="rounded-none" src="{% static 'svgs/block16.svg' %}" alt="image" />
                      </div>
                      <span>Netcon UPS</span>
                    </a>
                  </li>
                </ul>
                <!-- /.row -->
              </li>
              <!-- /.mega-menu-content -->
            </ul>
            <!-- /.dropdown-menu -->
          </li>
          <li class="nav-item">
            <a class="nav-link font-bold tracking-[-0.01rem] hover:!text-[#605dba] after:!text-[#605dba]" href="" data-bs-toggle="dropdown">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link font-bold tracking-[-0.01rem] hover:!text-[#605dba] after:!text-[#605dba]" href="" data-bs-toggle="dropdown">Become A Partner</a>
          </li>
        </ul>
        <!-- /.navbar-nav -->
        <div class="offcanvas-footer xl:hidden lg:hidden">
          <div>
            <a href="mailto:first.last@email.com" class="link-inverse">info@netconenterprise.com</a>
            <br /> 00 (91) 9567 9495 26<br />
            <nav class="nav social social-white mt-4">
              <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-twitter before:content-['\ed59'] !text-white text-[1rem]"></i></a>
              <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-facebook-f before:content-['\eae2'] !text-white text-[1rem]"></i></a>
              <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-dribbble before:content-['\eaa2'] !text-white text-[1rem]"></i></a>
              <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-instagram before:content-['\eb9c'] !text-white text-[1rem]"></i></a>
              <a class="text-[#cacaca] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 motion-reduce:transition-none hover:translate-y-[-0.15rem] m-[0_.7rem_0_0]" href="#"><i class="uil uil-youtube before:content-['\edb5'] !text-white text-[1rem]"></i></a>
            </nav>
            <!-- /.social -->
          </div>
        </div>
        <!-- /.offcanvas-footer -->
      </div>
      <!-- /.offcanvas-body -->
    </div>
    <!-- /.navbar-collapse -->
    <div class="navbar-other w-full !flex !ml-auto">
      <ul class="navbar-nav !flex-row !items-center !ml-auto">
        <li class="nav-item">
          <nav class="nav social social-muted justify-end text-right">
            <a class="m-[0_0_0_.7rem] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 hover:translate-y-[-0.15rem]" href="#"><i class="uil uil-linkedin before:content-['\ed59'] text-[1rem] text-[#5daed5]"></i></a>
            <a class="m-[0_0_0_.7rem] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 hover:translate-y-[-0.15rem]" href="#"><i class="uil uil-facebook-f before:content-['\eae2'] text-[1rem] text-[#4470cf]"></i></a>
            <a class="m-[0_0_0_.7rem] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 hover:translate-y-[-0.15rem]" href="#"><i class="uil uil-dribbble before:content-['\eaa2'] text-[1rem] text-[#e94d88]"></i></a>
            <a class="m-[0_0_0_.7rem] text-[1rem] transition-all duration-[0.2s] ease-in-out translate-y-0 hover:translate-y-[-0.15rem]" href="#"><i class="uil uil-instagram before:content-['\eb9c'] text-[1rem] text-[#d53581]"></i></a>
          </nav>
          <!-- /.social -->
        </li>
        <li class="nav-item xl:hidden lg:hidden">
          <button class="hamburger offcanvas-nav-btn"><span></span></button>
        </li>
      </ul>
      <!-- /.navbar-nav -->
    </div>
    <!-- /.navbar-other -->
  </div>
  <!-- /.container -->
</nav>
<!--  -->

netcon_web/core/templates/home/about.html
{% load static %}
<section class="wrapper !bg-[#ffffff]">
  <div class="container py-5 xl:!py-[5rem] lg:!py-[5rem] md:!py-[5rem]">
    <div class="flex flex-wrap mx-[-15px] items-start ">
      <div class="xl:w-5/12 lg:w-5/12 w-full flex-[0_0_auto] px-[15px] max-w-full xl:!sticky lg:!sticky mt-[50px]" style="top: 8rem;">
        <h3 class="text-[calc(1.345rem_+_1.14vw)] !leading-[1.2] xl:text-[2.2rem] mb-5">Our Story: Bridging Innovation and Infrastructure</h3>
        <p class="!mb-7">Founded in 2021, Netcon Enterprise Private Limited has rapidly emerged as a formidable leader in the manufacturing of UPS systems, control cables, networking cables, network racks, IP enclosures, and security systems</p>
        <a href="#" class="btn btn-lg btn-navy text-white !bg-[#343f52] border-[#343f52] hover:text-white hover:bg-[#343f52] hover:border-[#343f52] focus:shadow-[rgba(82,92,108,1)] active:text-white active:bg-[#343f52] active:border-[#343f52] disabled:text-white disabled:bg-[#343f52] disabled:border-[#343f52] btn-icon btn-icon-end">More Details <i class="uil uil-arrow-up-right ml-[.3rem] before:content-['\e950']"></i></a>
      </div>
      <!-- /column -->
      <div class="xl:w-6/12 lg:w-6/12 w-full flex-[0_0_auto] px-[15px] max-w-full ml-auto mt-[50px]">
        <div class="card !bg-[#fdf1f8] !mb-6">
          <div class="card-body flex flex-row p-[40px]">
            <div>
              <img src="{% static 'img/icons/lineal/search-2.svg' %}" class="svg-inject icon-svg icon-svg-md !w-[2.6rem] !h-[2.6rem] text-[#e668b3] text-fuchsia mr-5" alt="image" />
            </div>
            <div>
              <h3 class="text-[1.05rem] mb-2">Our Vision</h3>
              <p class="!mb-0">Our vision is to be a global leader in power and connectivity solutions, continuously evolving our products to meet the dynamic needs of the industry and drive innovation and growth</p>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
        <div class="card !bg-[#eff7fa] !mb-6">
          <div class="card-body flex flex-row p-[40px]">
            <div>
              <img src="{% static 'img/icons/lineal/puzzle-2.svg' %}" class="svg-inject icon-svg icon-svg-md !w-[2.6rem] !h-[2.6rem] text-[#54a8c7] text-aqua mr-5" alt="image" />
            </div>
            <div>
              <h3 class="text-[1.05rem] mb-2">Our Mission</h3>
              <p class="!mb-0">Delivering innovative power and connectivity solutions that improve efficiency, reliability, and performance, setting industry standards through excellence and technology</p>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
        <div class="card !bg-[#fff8ee] !mb-6">
          <div class="card-body flex flex-row p-[40px]">
            <div>
              <img src="{% static 'img/icons/lineal/smartphone.svg' %}" class="svg-inject icon-svg icon-svg-md !w-[2.6rem] !h-[2.6rem] text-[#fab758] text-yellow mr-5" alt="image" />
            </div>
            <div>
              <h3 class="text-[1.05rem] mb-2">Why NetCon</h3>
              <p class="!mb-0">Quality is at the core of our operations. We employ rigorous controls and advanced manufacturing to exceed customer expectations, adhering to global standards and certifications</p>
            </div>
          </div>
          <!-- /.card-body -->
        </div>
      
        <!-- /.card -->
      </div>
      <!-- /column -->
    </div>
    <!-- /.row -->

    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>

netcon_web/core/templates/home/products.html
{% load static %}
<div class="container mt-10">
  <div class="flex flex-wrap mx-[-15px]">
    <div class="md:w-11/12 lg:w-8/12 xl:w-7/12 xxl:w-6/12 w-full flex-[0_0_auto] px-[15px] max-w-full !mx-auto !text-center">
      <h2 class="text-[calc(1.345rem_+_1.14vw)] font-bold leading-[1.2] xl:text-[2.2rem] mb-4">
        The extensive range of
        <span class="rotator-fade text-[#1da44c]">products we deliver...,solutions we deliver...</span>
      </h2>
      <p class="lead !text-[1.05rem] !leading-[1.55] !font-normal mb-12">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis iste, temporibus quasi voluptatum</p>
    </div>
  </div>

  <section class="bg-white">
    <div class="flex flex-wrap mx-[-15px] xl:mx-[-10px] lg:mx-[-10px] md:mx-[-10px] mt-[-20px]">
      <div class="xl:w-4/12 lg:w-4/12 md:w-4/12 flex-[0_0_auto] xl:px-[10px] lg:px-[10px] md:px-[10px] px-[12px] max-w-full mt-[20px]">
        <figure class="overlay overlay-2 hover-scale color rounded group">
          <a class="!relative block z-[3] cursor-pointer inset-0" href="#">
            <img loading="lazy" src="{% static 'products/cable.jpg' %}" alt="cable" class="rounded-[0.4rem] responsive-img" /></a>
          <figcaption class="group-hover:opacity-100 absolute w-full h-full opacity-0 text-center px-2 py-2 inset-0 z-[5] pointer-events-none p-1">
            <h5 class="from-top !mb-1">Cable</h5>
            <p class="from-bottom">Click to view more</p>
          </figcaption>
        </figure>
      </div>

      <div class="xl:w-4/12 lg:w-4/12 md:w-4/12 flex-[0_0_auto] xl:px-[10px] lg:px-[10px] md:px-[10px] px-[12px] max-w-full mt-[20px]">
        <figure class="overlay overlay-2 hover-scale color rounded group">
          <a class="!relative block z-[3] cursor-pointer inset-0" href="#">
            <img loading="lazy" src="{% static 'products/cable.jpg' %}" alt="cable" class="rounded-[0.4rem] responsive-img" /></a>
          <figcaption class="group-hover:opacity-100 absolute w-full h-full opacity-0 text-center px-2 py-2 inset-0 z-[5] pointer-events-none p-1">
            <h5 class="from-top !mb-1">Cable</h5>
            <p class="from-bottom">Click to view more</p>
          </figcaption>
        </figure>
      </div>

      <div class="xl:w-4/12 lg:w-4/12 md:w-4/12 flex-[0_0_auto] xl:px-[10px] lg:px-[10px] md:px-[10px] px-[12px] max-w-full mt-[20px]">
        <figure class="overlay overlay-2 hover-scale color rounded group">
          <a class="!relative block z-[3] cursor-pointer inset-0" href="#">
            <img loading="lazy" src="{% static 'products/cable.jpg' %}" alt="cable" class="rounded-[0.4rem] responsive-img" /></a>
          <figcaption class="group-hover:opacity-100 absolute w-full h-full opacity-0 text-center px-2 py-2 inset-0 z-[5] pointer-events-none p-1">
            <h5 class="from-top !mb-1">Cable</h5>
            <p class="from-bottom">Click to view more</p>
          </figcaption>
        </figure>
      </div>
      <div class="xl:w-4/12 lg:w-4/12 md:w-4/12 flex-[0_0_auto] xl:px-[10px] lg:px-[10px] md:px-[10px] px-[12px] max-w-full mt-[20px]">
        <figure class="overlay overlay-2 hover-scale color rounded group">
          <a class="!relative block z-[3] cursor-pointer inset-0" href="#">
            <img loading="lazy" src="{% static 'products/cable2.jpg' %}" alt="cable" class="rounded-[0.4rem] responsive-img" /></a>
          <figcaption class="group-hover:opacity-100 absolute w-full h-full opacity-0 text-center px-2 py-2 inset-0 z-[5] pointer-events-none p-1">
            <h5 class="from-top !mb-1">Cable</h5>
            <p class="from-bottom">Click to view more</p>
          </figcaption>
        </figure>
      </div>
      <div class="xl:w-4/12 lg:w-4/12 md:w-4/12 flex-[0_0_auto] xl:px-[10px] lg:px-[10px] md:px-[10px] px-[12px] max-w-full mt-[20px]">
        <figure class="overlay overlay-2 hover-scale color rounded group">
          <a class="!relative block z-[3] cursor-pointer inset-0" href="#">
            <img loading="lazy" src="{% static 'products/cable2.jpg' %}" alt="cable" class="rounded-[0.4rem] responsive-img" /></a>
          <figcaption class="group-hover:opacity-100 absolute w-full h-full opacity-0 text-center px-2 py-2 inset-0 z-[5] pointer-events-none p-1">
            <h5 class="from-top !mb-1">Cable</h5>
            <p class="from-bottom">Click to view more</p>
          </figcaption>
        </figure>
      </div>
      <div class="xl:w-4/12 lg:w-4/12 md:w-4/12 flex-[0_0_auto] xl:px-[10px] lg:px-[10px] md:px-[10px] px-[12px] max-w-full mt-[20px]">
        <figure class="overlay overlay-2 hover-scale color rounded group">
          <a class="!relative block z-[3] cursor-pointer inset-0" href="#">
            <img loading="lazy" src="{% static 'products/cable2.jpg' %}" alt="cable" class="rounded-[0.4rem] responsive-img" /></a>
          <figcaption class="group-hover:opacity-100 absolute w-full h-full opacity-0 text-center px-2 py-2 inset-0 z-[5] pointer-events-none p-1">
            <h5 class="from-top !mb-1">Cable</h5>
            <p class="from-bottom">Click to view more</p>
          </figcaption>
        </figure>
      </div>
    </div>
  </section>
</div>

<style>
  .responsive-img {
    max-width: 100%;
    height: auto;
  }
</style>